sudo: true
language: ruby
rvm:
  - 2.5.0
before_install:
  - gem install bundler -v 1.16.1
  - bundle install
  - curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash
  - ./install_keys.sh

jobs:
  include:
    - stage: gem release
      if: branch = master
      rvm: 2.5.0
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        gem: litterbox
        api_key: $RUBYGEMS_API_KEY
        on: master
    - stage: GitHub Release
      if: branch = master
      rvm: 2.5.0
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: Habitat Release
      if: branch = master
      script:
         - |
           echo "Deploying to bldr.habitat.sh ..."
           bundle install
           bundle exec ./bin/litterbox build
           bundle exec ./bin/litterbox upload
